name: 'OpenFGA Model Testing Action'
description: 'Github Action for testing your OpenFGA Authorization Model'
branding:
  icon: 'align-center'
  color: 'green'

inputs:
  test_path:
    description: 'Path to the test file or folder'
    required: false
    default: '.'
  test_files_pattern:
    description: 'Pattern to match the test files'
    required: false
    default: '*.fga.yaml'

runs:
  using: composite
  steps:
    - name: Install OpenFGA CLI
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: openfga/cli
        cache: enable
    - name: Run OpenFGA CLI
      shell: bash
      run: |
          while IFS= read -r -d '' test_file
          do
            ((test_files_count+=1))
            echo "Running FGA test file ${test_file}"
            fga model test --tests "${test_file}"
          done <   <(find ${{ inputs.test_path }} -name "${{ inputs.test_files_pattern }}" -print0)
  
          if [[ ${test_files_count} -eq 0 ]]; then
            echo "No FGA test file found for path '${{ inputs.test_path }}' and pattern '${{ inputs.test_files_pattern }}'"
            exit 1
          fi