name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  undraft-release:
    permissions:
      contents: write
    uses: openfga/.github/.github/workflows/undraft-release.yml@835baf31562809ad9eb884c73efc5b79318f700f # pin@main
